server:
  port: 8000

spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: mircroservice-provider-user

logging:
  level:
      root: INFO
      org.hibernate: INFO
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

management:
  security:
    enabled: false

info:
  app:
    name: @project.artifactId@
    ecoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      targer: @java.version@

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      # 自定义的元数据，key/value可以随便写
      my-metadata: fuck2data
